version: '3'


services:
  backend:
    build: ./backend/server
    restart: always
    stop_grace_period: 10s
    depends_on:
      - postgres
    ports:
      - "3113:3113"
    networks:
      - default
      - internal_network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5050:5050"
    networks:
      - default

  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./backend/server/init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "3114:5432"
    networks:
      - internal_network
      
  adminer:
    image: adminer:latest
    restart: always 
    ports:
      - 8085:8080
    networks:
      - default
      - internal_network


volumes:
  postgres-data:


networks:
  default:
  internal_network:
    internal: true
