FROM ubuntu:latest

WORKDIR /home/server/

ENV PYTHONUNBUFFERED 1
ENV TZ  Europe/Moscow
ENV ENV PRODUCTION

#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#RUN apt-get update && apt-get install firefox python3-pip -y
RUN apt-get update && apt-get install python3-pip -y

COPY requirements.txt ./
RUN pip3 install -r requirements.txt
COPY . .

CMD [ "gunicorn", "--bind", "0.0.0.0:3113", "--worker-class", "gevent", "--worker-connections", "1000", "--workers", "3", "--log-level", "INFO", "--timeout", "120", "server:app" ]
